### PR TITLE
Add rudimentary support for Python 3

### PR DESCRIPTION
**Pull request by alexwlchan**
Right now, if you run `pip3 install pinboard` in a Python 3 virtualenv, it fails to install:

```console
$ pip install pinboard
Collecting pinboard
  Downloading pinboard-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/0d/p_z4b6f90g1gc8h9y87w0td80000gn/T/pip-build-87w6n5fp/pinboard/setup.py", line 6, in <module>
        from pinboard import metadata
      File "/private/var/folders/0d/p_z4b6f90g1gc8h9y87w0td80000gn/T/pip-build-87w6n5fp/pinboard/pinboard/__init__.py", line 1, in <module>
        from .pinboard import Pinboard
      File "/private/var/folders/0d/p_z4b6f90g1gc8h9y87w0td80000gn/T/pip-build-87w6n5fp/pinboard/pinboard/pinboard.py", line 5, in <module>
        import urllib2
    ImportError: No module named 'urllib2'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0d/p_z4b6f90g1gc8h9y87w0td80000gn/T/pip-build-87w6n5fp/pinboard
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

This patch adds basic support for Python 3. I ran `2to3` over the `pinboard` directory, and added a small compatibility file for the renamed parts of the standard library. Normally I’d use `six`, but you seem to be dependency-averse so I just wrote a new one.

I’ve tested this to the point that it installs and imports correctly in Python 3, but nothing more than that. There may be other subtle bugs lurking (string encoding is the big one) that I haven’t addressed. I might be using this library under Python 3, so I’ll open PRs if/when I find more Python 3-specific bugs.

### CODE REVIEW

**Review by dlo — CHANGES_REQUESTED** [review]
Sorry for the delayed review. The build fails on Python 2.7. Could you take a look and see what's causing the issue? Thanks!

**Comment by alexwlchan** [comment]
Oops, I screwed up one of the compatibility imports. Hopefully fixed now.

**Comment by alexwlchan** [comment]
At last, a version that passes green. :-)

**Comment by Uninen** [comment]
I get "JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)" with this patch and python 3.5.2. Don't know if it's me not knowing how to use it or the code, tho :)

```
In [7]: pb = pinboard.Pinboard(api_token)

In [8]: pb.posts.update()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-bea215ae1a86> in <module>()
----> 1 pb.posts.update()

/home/uninen/projects/unessanet/django/pylib/pinboard/pinboard.py in __call__(self, *args, **kwargs)
    181         else:
    182             if parse_response:
--> 183                 json_response = json.load(response)
    184 
    185                 for field in Pinboard.DATE_FIELDS:

/usr/lib/python3.5/json/__init__.py in load(fp, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    266         cls=cls, object_hook=object_hook,
    267         parse_float=parse_float, parse_int=parse_int,
--> 268         parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    269 
    270 

/usr/lib/python3.5/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    310     if not isinstance(s, str):
    311         raise TypeError('the JSON object must be str, not {!r}'.format(
--> 312                             s.__class__.__name__))
    313     if s.startswith(u'\ufeff'):
    314         raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",

TypeError: the JSON object must be str, not 'bytes'

```

**Comment by Uninen** [comment]
I finally got round to fixing this, the relevant one-line fix is at this commit: https://github.com/Uninen/pinboard.py/commit/71d5ea44e39de303cb9ac1e69ab887545d13367a :)

**Comment by dlo** [comment]
Awesome, thanks @Uninen!

**Comment by dlo** [comment]
@alexwlchan could you update with @Uninen's attached fix? thanks :)

**Comment by alexwlchan** [comment]
Looks like you got to Python 3 support without this patch, so closing.

**Pull request closed without merging**
